
services:
  - type: web
    name: discord-masquerade-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    plan: free
    envVars:
      - key: DISCORD_BOT_TOKEN
        sync: false
    healthCheckPath: /
